version: 0.0
os: linux 

files:
    - source: / 
      destination: /home/ubuntu/backend
      timeout: 300
     
      


hooks:
   
  AfterInstall:
    - location: script/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: script/RunFunctionalTests.sh
      timeout: 3600
